import type {Metadata} from 'next';
import {Lexend} from 'next/font/google';
import './globals.css';

const lexend = Lexend({
	subsets: ['latin'],
});



export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${lexend.className} antialiased`}>
				<div className="flex items-center justify-center h-screen bg-space-700 text-midnight-100">
					{children}
				</div>
			</body>
		</html>
	);
}
